package session1;

import java.util.HashMap;
import java.util.Map;

public class CountriesWithCapitals {

    public static String findCapital( String country){

        //    Key    Value
        Map<String, String> capitals = new HashMap<>();
            capitals.put("afghanistan", "Kabul");
            capitals.put("albania", "Tirana");
            capitals.put("algeria", "Algiers");
            capitals.put("american samoa", "Pago Pago");
            capitals.put("andorra", "Andorra la Vella");
            capitals.put("angola", "Luanda");
            capitals.put("anguilla", "The Valley");
            capitals.put("antigua and barbuda", "Saint John's");
            capitals.put("argentina", "Buenos Aires");
            capitals.put("armenia", "Yerevan");
            capitals.put("aruba", "Oranjestad");
            capitals.put("australia", "Canberra");
            capitals.put("austria", "Vienna");
            capitals.put("azerbaijan", "Baku");
            capitals.put("bahamas", "Nassau");
            capitals.put("bahrain", "Manama");
            capitals.put("bangladesh", "Dhaka");
            capitals.put("barbados", "Bridgetown");
            capitals.put("belarus", "Minsk");
            capitals.put("belgium", "Brussels");
            capitals.put("belize", "Belmopan");
            capitals.put("benin", "Porto-Novo");
            capitals.put("bermuda", "Hamilton");
            capitals.put("bhutan", "Thimphu");
            capitals.put("bolivia", "La Paz");
            capitals.put("bosnia and herzegovina", "Sarajevo");
            capitals.put("botswana", "Gaborone");
            capitals.put("brazil", "Brasilia");
            capitals.put("british indian ocean territory", "Diego Garcia");
            capitals.put("british virgin islands", "Road Town");
            capitals.put("brunei", "Bandar Seri Begawan");
            capitals.put("bulgaria", "Sofia");
            capitals.put("burkina faso", "Ouagadougou");
            capitals.put("burma", "Naypyidaw");
            capitals.put("burundi", "Bujumbura");
            capitals.put("cambodia", "Phnom Penh");
            capitals.put("cameroon", "Yaounde");
            capitals.put("canada", "Ottawa");
            capitals.put("cape verde", "Praia");
            capitals.put("cayman islands", "George Town");
            capitals.put("central african republic", "Bangui");
            capitals.put("chad", "N'Djamena");
            capitals.put("chile", "Santiago");
            capitals.put("china", "Beijing");
            capitals.put("colombia", "Bogota");
            capitals.put("comoros", "Moroni");
            capitals.put("congo democratic republic", "Kinshasa");
            capitals.put("congo republic", "Brazzaville");
            capitals.put("cook islands", "Avarua");
            capitals.put("costa rica", "San Jose");
            capitals.put("cote divoire", "Yamoussoukro");
            capitals.put("croatia", "Zagreb");
            capitals.put("cuba", "Havana");
            capitals.put("cyprus", "Nicosia");
            capitals.put("czech republic", "Prague");
            capitals.put("denmark", "Copenhagen");
            capitals.put("djibouti", "Djibouti");
            capitals.put("dominica", "Roseau");
            capitals.put("dominican republic", "Santo Domingo");
            capitals.put("east timor", "Dili");
            capitals.put("egypt", "Cairo");
            capitals.put("el salvador", "San Salvador");
            capitals.put("england", "London");
            capitals.put("equador", "Quito");
            capitals.put("equatorial guinea", "Malabo");
            capitals.put("eritrea", "Asmara");
            capitals.put("estonia", "Tallinn");
            capitals.put("ethiopia", "Addis Ababa");
            capitals.put("falkland islands", "Stanley");
            capitals.put("faroe islands", "Torshavn");
            capitals.put("fiji", "Suva");
            capitals.put("finland", "Helsinki");
            capitals.put("france", "Paris");
            capitals.put("french polynesia", "Papeete");
            capitals.put("gabon", "Libreville");
            capitals.put("gambia", "Banjul");
            capitals.put("georgia", "Tbilisi");
            capitals.put("germany", "Berlin");
            capitals.put("ghana", "Accra");
            capitals.put("gibraltar", "Gibraltar");
            capitals.put("great britain", "Athens");
            capitals.put("greece", "Nuuk");
            capitals.put("greenland", "Saint George's");
            capitals.put("grenada", "Hagatna");
            capitals.put("guam", "Guatemala City");
            capitals.put("guatemala", "Saint Peter Port");
            capitals.put("guernsey", "Conakry");
            capitals.put("guinea", "Bissau");
            capitals.put("guinea bissau", "Georgetown");
            capitals.put("guyana", "Port-au-Prince");
            capitals.put("haiti", "Port-au-Prince");
            capitals.put("honduras", "Tegucigalpa");
            capitals.put("hong kong", "Hong Kong");
            capitals.put("hungary", "Budapest");
            capitals.put("iceland", "Reykjavik");
            capitals.put("india", "New Delhi");
            capitals.put("indonesia", "Jakarta");
            capitals.put("iran", "Tehran");
            capitals.put("iraq", "Baghdad");
            capitals.put("ireland", "Dublin");
            capitals.put("isle of man", "Douglas");
            capitals.put("israel", "Jerusalem");
            capitals.put("italy", "Rome");
            capitals.put("jamaica", "Kingston");
            capitals.put("japan", "Tokyo");
            capitals.put("jersey", "Saint Helier");
            capitals.put("jordan", "Amman");
            capitals.put("kazakhstan", "Astana");
            capitals.put("kenya", "Nairobi");
            capitals.put("kiribati", "Tarawa");
            capitals.put("kuwait", "Kuwait City");
            capitals.put("kyrgyzstan", "Bishkek");
            capitals.put("laos", "Vientiane");
            capitals.put("latvia", "Riga");
            capitals.put("lebanon", "Beirut");
            capitals.put("lesotho", "Maseru");
            capitals.put("liberia", "Monrovia");
            capitals.put("libya", "Tripoli");
            capitals.put("liechtenstein", "Vaduz");
            capitals.put("lithuania", "Vilnius");
            capitals.put("luxembourg", "Luxembourg");
            capitals.put("macau", "N/A");
            capitals.put("macedonia", "Skopje");
            capitals.put("madagascar", "Antananarivo");
            capitals.put("malawi", "Lilongwe");
            capitals.put("malaysia", "Kuala Lumpur");
            capitals.put("maledives", "Male");
            capitals.put("mali", "Bamako");
            capitals.put("malta", "Valletta");
            capitals.put("marshall islands", "Majuro");
            capitals.put("martinique", "Fort-de-France");
            capitals.put("mauretania", "Nouakchott");
            capitals.put("mauritius", "Port Louis");
            capitals.put("mexico", "Mexico City");
            capitals.put("micronesia", "Palikir");
            capitals.put("moldova", "Chisinau");
            capitals.put("monaco", "Monaco");
            capitals.put("mongolia", "Ulaanbaatar");
            capitals.put("montserrat", "Plymouth");
            capitals.put("morocco", "Rabat");
            capitals.put("mozambique", "Maputo");
            capitals.put("namibia", "Windhoek");
            capitals.put("nauru", "Yaren");
            capitals.put("nepal", "Kathmandu");
            capitals.put("netherlands", "Amsterdam");
            capitals.put("netherlands antilles", "Willemstad");
            capitals.put("new zealand", "Wellington");
            capitals.put("nicaragua", "Managua");
            capitals.put("niger", "Niamey");
            capitals.put("nigeria", "Abuja");
            capitals.put("niue", "Alofi");
            capitals.put("norfolk island", "Kingston");
            capitals.put("northern mariana islands", "Saipan");
            capitals.put("north korea", "Pyongyang");
            capitals.put("norway", "Oslo");
            capitals.put("oman", "Muscat");
            capitals.put("pakistan", "Islamabad");
            capitals.put("palau", "Melekeok");
            capitals.put("panama", "Panama City");
            capitals.put("papua new guinea", "Port Moresby");
            capitals.put("paraquay", "Asuncion");
            capitals.put("peru", "Lima");
            capitals.put("philippines", "Manila");
            capitals.put("pitcairn islands", "Adamstown");
            capitals.put("poland", "Warsaw");
            capitals.put("portugal", "Lisbon");
            capitals.put("puerto rico", "San Juan");
            capitals.put("qatar", "Doha");
            capitals.put("romania", "Bucharest");
            capitals.put("russia", "Moscow");
            capitals.put("rwanda", "Kigali");
            capitals.put("saint helena", "Jamestown");
            capitals.put("saint kitts and nevis", "Basseterre");
            capitals.put("saint lucia", "Castries");
            capitals.put("saint pierre and miquelon", "Saint-Pierre");
            capitals.put("saint vincent and the grenadines", "Kingstown");
            capitals.put("samoa", "Apia");
            capitals.put("san marino", "San Marino");
            capitals.put("sao tome and principe", "Sao Tome");
            capitals.put("saudi arabia", "Riyadh");
            capitals.put("scotland", "Edinburgh");
            capitals.put("senegal", "Dakar");
            capitals.put("serbia montenegro", "Belgrade");
            capitals.put("seychelles", "Victoria");
            capitals.put("sierra leone", "Freetown");
            capitals.put("singapore", "Singapore");
            capitals.put("slovakia", "Bratislava");
            capitals.put("slovenia", "Ljubljana");
            capitals.put("solomon islands", "Honiara");
            capitals.put("somalia", "Mogadishu");
            capitals.put("south africa", "Pretoria");
            capitals.put("south georgia", "King Edward Point");
            capitals.put("south korea", "Seoul");
            capitals.put("spain", "Madrid");
            capitals.put("sri lanka", "Colombo");
            capitals.put("sudan", "Khartoum");
            capitals.put("suriname", "Paramaribo");
            capitals.put("swaziland", "Mbabane");
            capitals.put("sweden", "Stockholm");
            capitals.put("switzerland", "Bern");
            capitals.put("syria", "Damascus");
            capitals.put("taiwan", "Taipei");
            capitals.put("tajikistan", "Dushanbe");
            capitals.put("tanzania", "Dar es Salaam");
            capitals.put("thailand", "Bangkok");
            capitals.put("tibet", "Lhasa");
            capitals.put("togo", "Lome");
            capitals.put("tonga", "Nuku'alofa");
            capitals.put("trinidad and tobago", "Port of Spain");
            capitals.put("tunisia", "Tunis");
            capitals.put("turkey", "Ankara");
            capitals.put("turkmenistan", "Ashgabat");
            capitals.put("turks and caicos islands", "Grand Turk");
            capitals.put("tuvalu", "Funafuti");
            capitals.put("uganda", "Kampala");
            capitals.put("ukraine", "Kyiv");
            capitals.put("united arab emirates", "Abu Dhabi");
            capitals.put("uruquay", "Montevideo");
            capitals.put("usa", "Washington DC");
            capitals.put("uzbekistan", "Tashkent");
            capitals.put("vanuatu", "Port-Vila");
            capitals.put("vatican city", "Vatican City");
            capitals.put("venezuela", "Caracas");
            capitals.put("vietnam", "Hanoi");
            capitals.put("virgin islands", "Charlotte Amalie");
            capitals.put("wales", "Cardiff");
            capitals.put("wallis and futuna", "Mata-Utu");
            capitals.put("yemen", "Sanaa");
            capitals.put("zambia", "Lusaka");
            capitals.put("zimbabwe", "Harare");


            return capitals.get(country); //washington dc
    }



}
